# Generated by Django 6.0.5 on 2026-06-03 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Kategori')),
                ('description', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('icon', models.CharField(default='☕', help_text='Emoji atau icon untuk kategori', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=300, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='No. Telepon')),
                ('date', models.DateField(verbose_name='Tanggal')),
                ('time', models.TimeField(verbose_name='Waktu')),
                ('guests', models.PositiveIntegerField(verbose_name='Jumlah Tamu')),
                ('message', models.TextField(blank=True, verbose_name='Pesan Tambahan')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('confirmed', 'Dikonfirmasi'), ('cancelled', 'Dibatalkan'), ('completed', 'Selesai')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reservasi',
                'verbose_name_plural': 'Reservasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='KopiKita', max_length=200)),
                ('tagline', models.CharField(default='Secangkir Kebahagiaan di Setiap Tegukan', max_length=500)),
                ('about_text', models.TextField(default='KopiKita adalah kedai kopi yang menyajikan kopi berkualitas tinggi dari biji pilihan Nusantara.')),
                ('address', models.TextField(default='Jl. Kopi Nikmat No. 42, Jakarta Selatan')),
                ('phone', models.CharField(default='+62 812-3456-7890', max_length=20)),
                ('email', models.EmailField(default='hello@kopikita.id', max_length=254)),
                ('opening_hours', models.CharField(default='Setiap Hari, 07:00 - 22:00', max_length=200)),
                ('instagram', models.URLField(blank=True, default='https://instagram.com/kopikita')),
                ('whatsapp', models.URLField(blank=True, default='https://wa.me/6281234567890')),
            ],
            options={
                'verbose_name': 'Pengaturan Situs',
                'verbose_name_plural': 'Pengaturan Situs',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Menu')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Harga (Rp)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Gambar')),
                ('is_available', models.BooleanField(default=True, verbose_name='Tersedia')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Menu Unggulan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'name'],
            },
        ),
    ]
